server:
  port: 8081

spring:
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'
  datasource:
    driver-class-name: 'org.mariadb.jdbc.Driver'
    url: 'jdbc:mariadb://localhost:3306/jm_universe'
    username: 'root'
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.MariaDBDialect'
        show_sql: true
        format_sql: true
        use_sql_comments: true

universe-url:
  human-system: 'http://localhost:8080'